import express from "express";
import cors from "cors";
import helmet from "helmet";
import dotenv from "dotenv";
import healthRoutes from "./features/health/health.routes";
import UserRoutes from "./features/users/users.routes";
import { connectDatabase } from "./config/database";
import { globalErrorHandler } from "./common/middleware/error.middleware";
dotenv.config();
const app = express();
app.use(cors());
app.use(helmet());
app.use(express.json());
app.use("/health", healthRoutes);
app.use("/users", UserRoutes);
app.use(globalErrorHandler);
export const startApp = async () => {
  await connectDatabase();
  return app;
};
